name: Rust CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: update linux
      run: sudo apt update 
    - name: update Rust
      run: make install
    - name: Check Rust versions
      run: make rust-version
    - name: Format
      run: make format
      working-directory: ./project
    - name: Lint
      run: make lint
      working-directory: ./project
    - name: Test
      run: make test
      working-directory: ./project
    - name: Build in Release Mode
      run: cargo build --release
      working-directory: ./project
    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: optimized-binary
        path: project/target/release/sqlite_operations
    - name: pull repository
      run: git pull
